import { jsPDF } from "jspdf";

export const generatePDFReport = (analysis, filename) => {
  const doc = new jsPDF();

  doc.setFontSize(22);
  doc.text("AI Resume Review Report", 20, 20);

  doc.setFontSize(12);

  doc.text(`Resume: ${filename}`, 20, 35);
  doc.text(`ATS Score: ${analysis.ats_score}/100`, 20, 45);

  doc.text("Missing Skills:", 20, 60);

  let y = 70;

  if (analysis.missing_skills.length === 0) {
    doc.text("None", 30, y);
    y += 10;
  } else {
    analysis.missing_skills.forEach((skill) => {
      doc.text(`• ${skill}`, 30, y);
      y += 10;
    });
  }

  y += 10;

  doc.text("AI Suggestions:", 20, y);

  y += 10;

  if (analysis.suggestions.length === 0) {
    doc.text("No suggestions. Resume looks good.", 30, y);
  } else {
    analysis.suggestions.forEach((suggestion) => {
      doc.text(`• ${suggestion}`, 30, y);
      y += 10;
    });
  }

  y += 15;

  doc.text("Generated by AI Resume Reviewer", 20, y);

  doc.save("Resume_Report.pdf");
};